import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex gap-4 w-full bg-slate-100 p-4">
          <Link href={'/'} className="hover:text-blue-500">
            Home
          </Link>
          <Link href={'/finances'} className="hover:text-blue-500">
            Finances
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}
